// <auto-generated />
using System;
using Jvs.OrgService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jvs.OrgService.Migrations
{
    [DbContext(typeof(OrgDbContext))]
    [Migration("20260618002158_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Jvs.OrgService.Entities.Department", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CreateById")
                        .HasColumnType("longtext")
                        .HasColumnName("create_by_id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_time");

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("dept_name");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("LeaderUserId")
                        .HasColumnType("longtext")
                        .HasColumnName("leader_user_id");

                    b.Property<string>("ParentId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("parent_id");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UpdateById")
                        .HasColumnType("longtext")
                        .HasColumnName("update_by_id");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("update_time");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("TenantId");

                    b.ToTable("org_dept", (string)null);
                });

            modelBuilder.Entity("Jvs.OrgService.Entities.Permission", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Component")
                        .HasColumnType("longtext");

                    b.Property<string>("CreateById")
                        .HasColumnType("longtext")
                        .HasColumnName("create_by_id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_time");

                    b.Property<string>("Icon")
                        .HasColumnType("longtext");

                    b.Property<string>("ParentId")
                        .HasColumnType("longtext")
                        .HasColumnName("parent_id");

                    b.Property<string>("Path")
                        .HasColumnType("longtext");

                    b.Property<string>("PermissionCode")
                        .HasColumnType("longtext")
                        .HasColumnName("permission_code");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("permission_name");

                    b.Property<byte>("PermissionType")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("permission_type");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UpdateById")
                        .HasColumnType("longtext")
                        .HasColumnName("update_by_id");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("update_time");

                    b.Property<bool>("Visible")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("org_permission", (string)null);
                });

            modelBuilder.Entity("Jvs.OrgService.Entities.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CreateById")
                        .HasColumnType("longtext")
                        .HasColumnName("create_by_id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_time");

                    b.Property<byte>("DataScopeType")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("data_scope_type");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleCode")
                        .HasColumnType("longtext")
                        .HasColumnName("role_code");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role_name");

                    b.Property<byte>("RoleType")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("role_type");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UpdateById")
                        .HasColumnType("longtext")
                        .HasColumnName("update_by_id");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("update_time");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("org_role", (string)null);
                });

            modelBuilder.Entity("Jvs.OrgService.Entities.RolePermission", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PermissionId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("permission_id");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.ToTable("org_role_permission", (string)null);
                });

            modelBuilder.Entity("Jvs.OrgService.Entities.UserRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("org_user_role", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
