// <auto-generated />
using System;
using Jvs.AuthService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jvs.AuthService.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    partial class AuthDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Jvs.AuthService.Entities.Company", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Address")
                        .HasColumnType("longtext")
                        .HasColumnName("address");

                    b.Property<string>("BankAccount")
                        .HasColumnType("longtext")
                        .HasColumnName("bank_account");

                    b.Property<string>("BankName")
                        .HasColumnType("longtext")
                        .HasColumnName("bank_name");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("company_name");

                    b.Property<string>("CreateById")
                        .HasColumnType("longtext")
                        .HasColumnName("create_by_id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_time");

                    b.Property<bool>("Enable")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("enable");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext")
                        .HasColumnName("phone");

                    b.Property<string>("SecondCompanyName")
                        .HasColumnType("longtext")
                        .HasColumnName("second_company_name");

                    b.Property<string>("SecondTaxNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("second_tax_number");

                    b.Property<string>("ShortName")
                        .HasColumnType("longtext")
                        .HasColumnName("short_name");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasColumnName("sort");

                    b.Property<string>("TaxNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("tax_number");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UpdateById")
                        .HasColumnType("longtext")
                        .HasColumnName("update_by_id");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("update_time");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("auth_company", (string)null);
                });

            modelBuilder.Entity("Jvs.AuthService.Entities.RefreshToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_time");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("token");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("auth_refresh_token", (string)null);
                });

            modelBuilder.Entity("Jvs.AuthService.Entities.Tenant", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AdminUserId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("admin_user_id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_time");

                    b.Property<string>("DeploymentType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("deployment_type");

                    b.Property<bool>("Enable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("GatewayUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("gateway_url");

                    b.Property<string>("Hosts")
                        .HasColumnType("longtext");

                    b.Property<string>("Icon")
                        .HasColumnType("longtext");

                    b.Property<string>("Logo")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ParentId")
                        .HasColumnType("longtext")
                        .HasColumnName("parent_id");

                    b.Property<string>("ShortName")
                        .HasColumnType("longtext")
                        .HasColumnName("short_name");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("update_time");

                    b.HasKey("Id");

                    b.ToTable("auth_tenant", (string)null);
                });

            modelBuilder.Entity("Jvs.AuthService.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("CancelFlag")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CreateById")
                        .HasColumnType("longtext")
                        .HasColumnName("create_by_id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_time");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("HeadImg")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("RealName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte?>("Sex")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("UpdateById")
                        .HasColumnType("longtext")
                        .HasColumnName("update_by_id");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("update_time");

                    b.Property<byte>("UserType")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("AccountName")
                        .IsUnique();

                    b.ToTable("auth_user", (string)null);
                });

            modelBuilder.Entity("Jvs.AuthService.Entities.UserCompany", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("CancelFlag")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("cancel_flag");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_time");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("update_time");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CompanyId")
                        .IsUnique();

                    b.ToTable("auth_user_company", (string)null);
                });

            modelBuilder.Entity("Jvs.AuthService.Entities.UserTenant", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("CancelFlag")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("cancel_flag");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_time");

                    b.Property<string>("DeptId")
                        .HasColumnType("longtext")
                        .HasColumnName("dept_id");

                    b.Property<string>("DeptName")
                        .HasColumnType("longtext")
                        .HasColumnName("dept_name");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("EmployeeNo")
                        .HasColumnType("longtext")
                        .HasColumnName("employee_no");

                    b.Property<string>("JobId")
                        .HasColumnType("longtext")
                        .HasColumnName("job_id");

                    b.Property<string>("JobName")
                        .HasColumnType("longtext")
                        .HasColumnName("job_name");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext")
                        .HasColumnName("phone");

                    b.Property<string>("RealName")
                        .HasColumnType("longtext")
                        .HasColumnName("real_name");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("update_time");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "TenantId")
                        .IsUnique();

                    b.ToTable("auth_user_tenant", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
